# Self-hosted Supabase on Railway Configuration
# This file contains the configuration for deploying Supabase services on Railway

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: supabase
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Supabase API (PostgREST)
  supabase-api:
    image: postgrest/postgrest:v11.2.2
    environment:
      PGRST_DB_URI: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/supabase
      PGRST_DB_SCHEMA: public,auth,extensions
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"
      PGRST_APP_SETTINGS_JWT_SECRET: ${JWT_SECRET}
      PGRST_APP_SETTINGS_JWT_EXP: 3600
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  # Supabase Auth (GoTrue)
  supabase-auth:
    image: supabase/gotrue:v2.143.0
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/supabase?search_path=auth
      GOTRUE_SITE_URL: ${SITE_URL}
      GOTRUE_URI_ALLOW_LIST: ${ADDITIONAL_REDIRECT_URLS}
      GOTRUE_DISABLE_SIGNUP: ${DISABLE_SIGNUP}
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: true
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM}
      GOTRUE_SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL}
      GOTRUE_SMTP_HOST: ${SMTP_HOST}
      GOTRUE_SMTP_PORT: ${SMTP_PORT}
      GOTRUE_SMTP_USER: ${SMTP_USER}
      GOTRUE_SMTP_PASS: ${SMTP_PASS}
      GOTRUE_SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
      GOTRUE_EXTERNAL_PHONE_ENABLED: ${ENABLE_PHONE_SIGNUP}
      GOTRUE_SMS_AUTOCONFIRM: ${ENABLE_PHONE_AUTOCONFIRM}
    ports:
      - "9999:9999"
    depends_on:
      - postgres

  # Supabase Realtime
  supabase-realtime:
    image: supabase/realtime:v2.25.66
    environment:
      PORT: 4000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: supabase
      DB_AFTER_CONNECT_QUERY: 'SET search_path TO _realtime'
      DB_ENC_KEY: supabaserealtime
      API_JWT_SECRET: ${JWT_SECRET}
      FLY_ALLOC_ID: ${FLY_ALLOC_ID}
      FLY_APP_NAME: ${FLY_APP_NAME}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      ERL_AFLAGS: -proto_dist inet_tcp
      ENABLE_TAILSCALE: "false"
      DNS_NODES: "''"
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  # Supabase Storage
  supabase-storage:
    image: supabase/storage-api:v0.43.11
    environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_KEY: ${SERVICE_KEY}
      POSTGREST_URL: http://supabase-api:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/supabase
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      REGION: us-east-1
      GLOBAL_S3_BUCKET: stub
      ENABLE_IMAGE_TRANSFORMATION: "true"
      IMGPROXY_URL: http://imgproxy:5001
    ports:
      - "5000:5000"
    volumes:
      - storage_data:/var/lib/storage
    depends_on:
      - postgres
      - supabase-api

  # Image Proxy for Storage
  imgproxy:
    image: darthsim/imgproxy:v3.8.0
    environment:
      IMGPROXY_BIND: ":5001"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /var/lib/storage
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_ENABLE_WEBP_DETECTION: "true"
    ports:
      - "5001:5001"
    volumes:
      - storage_data:/var/lib/storage

volumes:
  postgres_data:
  storage_data:

# Environment Variables Required
required_env_vars:
  - POSTGRES_PASSWORD: Strong password for PostgreSQL
  - JWT_SECRET: JWT secret key (256-bit recommended)
  - API_EXTERNAL_URL: External URL for API access
  - SITE_URL: Site URL for redirects
  - ANON_KEY: Anonymous key for public access
  - SERVICE_KEY: Service role key for admin access
  - SECRET_KEY_BASE: Secret key base for Realtime
  - SMTP_HOST: SMTP server host (optional)
  - SMTP_PORT: SMTP server port (optional)
  - SMTP_USER: SMTP username (optional)
  - SMTP_PASS: SMTP password (optional)
  - SMTP_ADMIN_EMAIL: Admin email address (optional)
  - SMTP_SENDER_NAME: Email sender name (optional)

# Generated Keys (these will be created)
generated_keys:
  - ANON_KEY: Generated anonymous JWT token
  - SERVICE_KEY: Generated service role JWT token
  - FLY_ALLOC_ID: Unique allocation ID
  - FLY_APP_NAME: Application name identifier